name: Github Actions Test

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - test-new-framework-hest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
        env:
          CI: 'true'
      - run: sudo apt-get install xvfb
      - name: npm test
        run: xvfb-run --auto-servernum npm test
        env:
          CI: 'true'
