name: Github Actions Testing

on:
  pull_request:
  push:
    branches:
      - master
      - dev
      - automate-publish
      - Teams

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
        env:
          CI: 'true'
