  
name: Building workflow

on:
  pull_request:
    branches:
      - master
      - dev

  push:
    branches-ignore:
      # Ignore any documentation pushes
      - 'document-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install
        run: npm ci
        env:
          CI: 'true'
      - run: sudo apt-get install xvfb
      - run: npm run deploy
        env:
          vscode_token: ${{ secrets.VSCE_TOKEN }}